### ISSUE TITLE
Light not updated when using /time

### ISSUE THREAD

**Issue by progval** [bravoserver/bravo#248] opened 2011-05-04 13:09 UTC
Hello,

I was night, and I used "/time 0". Here is the result: http://ompldr.org/vOGp1aQ

Regards,
ProgVal

**Comment by progval** [comment] 2011-05-04 13:13
PS: it gets updated when I put a dirt block.

**Comment by MostAwesomeDude** [comment] 2011-05-08 17:29
I'm not sure if this is a client bug or not. Something to examine later, I think.

**Comment by MostAwesomeDude** [comment] 2011-05-10 11:31
This is a dupe of #132, plus a client bug which will require more thought to work around.

**Closed as completed by MostAwesomeDude** 2011-05-10 11:31 UTC
