### ISSUE TITLE
Dug areas become pitch black when logging back in to server

### ISSUE THREAD

**Issue by JDShu** [bravoserver/bravo#210] opened 2011-04-12 02:57 UTC
After digging a hole, logging out of the server, and logging back in, the area that was dug will be pitch black. Placing a block nearby or digging out a block nearby will make everything look normal again but only until the next login.

**Comment by dbdii407** [comment] 2011-04-12 12:52
I mentioned this to Mr. Awesome a couple of days ago in a pull request, along with a screenshot http://min.us/mvpmXyE . There is still some issues with lighting that need to be worked out. Trust me, it's being worked on.

**Comment by MostAwesomeDude** [comment] 2011-05-10 11:30
This is a dupe of #132.

**Closed as completed by MostAwesomeDude** 2011-05-10 11:30 UTC
