### ISSUE TITLE
Water from broken ice will disappear

### ISSUE THREAD

**Issue by JDShu** [bravoserver/bravo#205] opened 2011-04-10 03:22 UTC
When you break a block of ice, the water disappears (when the water hooks are enabled).

**Comment by MostAwesomeDude** [comment] 2011-05-10 11:33
Does this still happen? I never could reproduce this.

**Comment by JDShu** [comment] 2011-05-10 15:31
Happens with the current bravo.ini example, when it is winter.

**Comment by oal** [comment] 2011-05-10 15:51
Happens to me as well, but it looks like the water hooks don't make a difference. It happens both with or without. My world is new, and I haven't had the chance to test it on an old world.

**Comment by JDShu** [comment] 2011-05-17 07:18
Took a look at it. It's because an ice block gets replaced by a water block when it's destroyed, as opposed to a spring. The simple solution would be to change that. Alternatively an ice block could save whether it is frozen water or frozen spring in the metadata.

**Comment by MostAwesomeDude** [comment] 2011-05-17 17:55
The metadata trick sounds preferable.

Sending from a mobile, pardon the brevity. ~ C.
On May 17, 2011 12:18 AM, "JDShu" <
reply@reply.github.com>
wrote:

**Comment by MostAwesomeDude** [comment] 2011-09-28 07:28
This was pulled in a long time ago. Closing.

**Closed as completed by MostAwesomeDude** 2011-09-28 07:28 UTC
Labels: Bug
