### ISSUE TITLE
Client Crash and server error on block modification

### ISSUE THREAD

**Issue by Varriount** [bravoserver/bravo#28] opened 2010-12-19 19:37 UTC
On windows, using python 2.6, I get this error whenever I modify a block - http://pastebin.com/xcnpiwP1
I don't know if this is just for windows, or happens on linux as well

**Comment by MostAwesomeDude** [comment] 2010-12-22 23:54
I can't see the pastebin; it'd be nice to have it reproduced here.

**Comment by MostAwesomeDude** [comment] 2010-12-24 15:33
Closing since (a) can't reproduce (b) can't see the traceback (c) this probably was fixed with one of the other chunk numpy fixes.

**Closed as completed by MostAwesomeDude** 2010-12-24 15:33 UTC
