### ISSUE TITLE
1KO block support (snow + shovel -> no snow)

### ISSUE THREAD

**Issue by tjvr** [bravoserver/bravo#147] opened 2011-03-06 09:23 UTC
After disabling all the snow-related plugins, and setting 'season = ' in the bravo.ini file, snow keeps coming back when I remove it with the shovel. 

If I remove it without using the shovel, it goes away permanently.

C: We need to support 1KO blocks, basically; blocks with a dig time of zero.

**Comment by MostAwesomeDude** [comment] 2011-03-06 19:37
If you place the snow by /giving it to yourself, does it still come back? Do any other tools do this?

**Comment by tjvr** [comment] 2011-03-06 20:21
In short: yes, no.

From a quick test, only the shovel does this (out of shovel, axe, pickaxe) and it doesn't matter how the snow is placed - so if I place the snow by /giving it to myself and then destroy it with the shovel, it comes back again.

**Comment by alucas** [comment] 2011-04-19 17:52
I think this is not realy a bug, just a feature not already implemented :

The dig protocol is composed of two packet. the first is send to the server when we start to dig a block. The last when the block is destroy. but some block are destroy instantly, like snow whith shovel, in that case the "end" packet seem not be send, but the block is destroy anyway. For exemple, torchs, flowers, mushrooms may have the same comportement.

We must add the system who care about the time to dig each blocks and this problem may be resolved.

**Comment by MostAwesomeDude** [comment] 2011-04-19 20:05
Tagging for 1.5 and changing the name to reflect the real problem: We have no support for 1KO blocks.

**Comment by MostAwesomeDude** [comment] 2011-04-21 21:45
http://wiki.vg/How_to_Write_a_Client#How_long_to_wait is relevant.

**Comment by MostAwesomeDude** [comment] 2011-04-29 21:22
The dig-policy branch will be used to implement this feature. A "speedy" dig policy, which breaks blocks immediately, has been written and works exactly as intended; a "notchy" dig policy is planned but blocked on getting a bit more data as to exactly how the formulae for dig times work. In particular, since we have neither ticks nor block strength, we cannot really use the Notchian code verbatim. (This is perfectly reasonable to me since we should not be using Notchian code directly.)

**Comment by MostAwesomeDude** [comment] 2011-05-04 07:42
Closing as fixed since dig-policy has been merged.

**Closed as completed by MostAwesomeDude** 2011-05-04 07:42 UTC
Labels: Feature, Bug, Beta Compatibility
