### ISSUE TITLE
Images URL using config server address in WorldMap

### ISSUE THREAD

**Issue by lilorox** [bravoserver/bravo#315] opened 2011-07-20 09:50 UTC
Hi,

I found a very small bug in the web interface when displaying the WorldMap.
I'm using bravoserver with nginx as a proxy and noticed that it was working fine except the display of the WorldMap.

nginx configuration snippet :
location /bravo {
                rewrite /bravo/(.+) /$1 break;
                proxy_pass http://localhost:8080/;
}

The image addresses in /myworld/worldmap are not loading because the URL stays in the form http://localhost:8080/myworld/worldmap/#,#

I'll try to submit a patch when I figure out what is not right ;)

Thanks,
LiLoRoX

**Comment by MostAwesomeDude** [comment] 2011-07-20 17:38
I remember that those URLs are kinda funky; they should be easy to fix though.

**Comment by MostAwesomeDude** [comment] 2011-10-08 01:32
So, I'm looking at the code loading the images, and I'm seeing that they should be loading fine because the code doing the URL generation is client-side. Is this still an issue?

**Comment by MostAwesomeDude** [comment] 2011-10-08 19:20
I went back through the history and found that this issue was filed prior to the worldmap being switched to use client-side URL generation. Since I can't reproduce it, I'm marking this as fixed. Reopen if it persists. Thanks!

**Closed as completed by MostAwesomeDude** 2011-10-08 19:20 UTC
