### ISSUE TITLE
Damaged items are repaired

### ISSUE THREAD

**Issue by progval** [bravoserver/bravo#238] opened 2011-05-02 09:34 UTC
Hi,

If I have a damaged item (sword, shovel, pickaxe, and so n), and I pick an item (grass, dirt, stone, and so on), all the damaged items are repaired.

Regards,
ProgVal

**Comment by progval** [comment] 2011-05-02 09:42
Reconnecting to the server also repairs the items.

**Comment by alucas** [comment] 2011-05-02 13:41
Damages are not already tracking in bravo.

**Comment by MostAwesomeDude** [comment] 2011-05-03 05:41
Closing as a duplicate of #70.

**Closed as completed by MostAwesomeDude** 2011-05-03 05:41 UTC
