### ISSUE TITLE
Torch Light

### ISSUE THREAD

**Issue by justinnoah** [bravoserver/bravo#71] opened 2011-01-20 13:34 UTC
The client crashed when I was placing torches (not output from the log to say why), reconnected and found that the torches stopped lighting the area.

http://i.imgur.com/sGeCI.png

**Comment by MostAwesomeDude** [comment] 2011-01-27 20:29
Does this crash still happen? I can't reproduce it.

**Comment by kingofkya** [comment] 2011-02-14 21:40
I have a running server with this problem git update pulled feb 13  Go to server @ core.buizel.net  go inside the castle.

http://www.box.net/shared/5zfmnlggeu

**Comment by MostAwesomeDude** [comment] 2011-02-27 09:07
Closing since I can't produce the crash.

**Closed as completed by MostAwesomeDude** 2011-02-27 09:07 UTC
Labels: Bug
