### ISSUE TITLE
Error after authenticating when using Ampoule

### ISSUE THREAD

**Issue by hikari-no-yume** [bravoserver/bravo#240] opened 2011-05-02 17:24 UTC
```
2011-05-02 18:22:51+0100 [BravoProtocol,0,127.0.0.1] Authenticating client, protocol version 11
2011-05-02 18:22:54+0100 [-] Unhandled error in Deferred:
2011-05-02 18:22:54+0100 [-] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1076, in gotResult
        _inlineCallbacks(r, g, deferred)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1063, in _inlineCallbacks
        deferred.callback(e.value)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 361, in callback
        self._startRunCallbacks(result)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 455, in _startRunCallbacks
        self._runCallbacks()
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 542, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/media/Docs/Projects/2011/Bravo/bravo/bravo/protocols/beta.py", line 942, in send_chunk
        packet = make_packet("prechunk", x=chunk.x, z=chunk.z, enabled=1)
    exceptions.AttributeError: 'NoneType' object has no attribute 'x'
```

**Comment by hikari-no-yume** [comment] 2011-05-02 17:26
Using MostAwesomeDude/bravo/master, at https://github.com/MostAwesomeDude/bravo/commit/1dd3bf853c0c570299599ec10801e42c13cbecb4

**Comment by hikari-no-yume** [comment] 2011-05-02 17:30
On oal's advice I disabled ampoule (Ubuntu Linux 11.04 here, no Windows). Seems to fix the problem. Renamed this issue to reflect this as it appears to be an ampoule-only issue.

**Comment by hikari-no-yume** [comment] 2011-05-02 17:34
Duplicate of https://github.com/MostAwesomeDude/bravo/issues/236

**Comment by progval** [comment] 2011-05-02 17:45
Sorry for closing this issue, I don't know how, why, or when I closed it.

**Comment by MostAwesomeDude** [comment] 2011-05-08 19:15
Closing as dupe of #236, which is also closed.

**Closed as completed by MostAwesomeDude** 2011-05-08 19:15 UTC
