### ISSUE TITLE
Block Placement, Night Time, Pickup, and Serializers.

### ISSUE THREAD

**Issue by dbdii407** [bravoserver/bravo#138] opened 2011-03-03 20:25 UTC
I'm sorry. I accidently pressed "Comment and Close" so I guess I have to redo this...

I wasn't able to get bravo server end to launch at first due to a problem with plugins/serializers.py line 94. What goes in the config exactly so that it launches without my modification?

Night time is also messed up. The sky will change dark but the land will not. There is also some random shadow error that appears when placing a block down. Some items I cannot pick up after throwing them on the ground (diamond, sticks, torches, etc...) and there is also an issue where if I place a block outside of the mountains, the block will float up one from where I placed it.

Hope I can get some knowledge on these issues! :)

My comment:
"What exact items can you not pick up?" diamond, sticks, torches, etc... "How did you place them on the ground?" Tried to craft a diamond pickaxe, but it wouldn't let me, so I exited out of crafting and they fell on the ground. Placed torches also do this when you try to take them off the wall. "Were they crafted, or spawned with /give?" Give "What do you mean be "outside of the mountains"" When you dig inside of a mountain. There's now an inside and outside of the mountain.

As for the serializer problem, I tried to find documentation on it but I couldn't find anything. I don't understand it.

**Comment by MostAwesomeDude** [comment] 2011-03-04 01:14
For future reference, bugs can be reopened.

As bravo.ini.example suggests, the path to a world needs to be a URL, not a path. This is for future compatibility with serializers which might not save to disk.

Lighting is still iffy; the day-glow nights and shadows are caused by lighting bugs.

Throwing things out of inventory is not quite supported. There are spots where it works and spots where it doesn't.

**Comment by dbdii407** [comment] 2011-03-05 17:34
And "and there is also an issue where if I place a block outside of the mountains, the block will float up one from where I placed it."?

**Comment by Varriount** [comment] 2011-03-05 18:16
Explain.

**Comment by dbdii407** [comment] 2011-03-08 20:13
Let's say you place a block at (0, 1, 0) (Where y=0 is the ground block), after placing it will go to (0, 2, 0) (as in, it will float a block above where it was intended to be placed)

According to what I see, this problem has been fixed.

**Comment by MostAwesomeDude** [comment] 2011-03-24 08:54
Closing since just about everything in this issue has been addressed. In the future, please separate out different problems into different tickets. Thanks.

**Closed as completed by MostAwesomeDude** 2011-03-24 08:54 UTC

**Comment by dbdii407** [comment] 2011-03-24 14:00
Thanks.
